LibraryMangementSystem/LibraryMangementSystem/Models/Loan.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryMangementSystem.Models
{
    public class Loan
    {
        public int LoanID { get; set; }
        public int MemberID { get; set; }
        public int BookID { get; set; }
        [Display(Name = "Loan Date")]
        public DateTime LoanDate { get; set; }
        [Display(Name = "Due Date")]
        public DateTime DueDate { get; set; }
        [Display(Name = "Return Date")]
        public DateTime? ReturnDate { get; set; }
        [Display(Name = "Penalty Cost")]
        public int PenaltyCost { get; set; } = 0;
        [Display(Name = "Loan Period")]
        public int LoanPeriod { get; set; }
        public bool Approved { get; set; }
        // nav properties
        public Book Book { get; set; }
        public Member Member { get; set; }
        
    }
}

LibraryMangementSystem/LibraryMangementSystem/Models/LoanViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryMangementSystem.Models
{
    public class LoanViewModel : Loan
    {
        [Display(Name = "Member Email")]
        public string MemberEmail { get; set; }
        [Display(Name = "Book Title")]
        public string BookTitle { get; set; }
    }
}

LibraryMangementSystem/LibraryMangementSystem/Controllers/LoansController.cs
using LibraryMangementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace LibraryMangementSystem.Controllers
{
    [Authorize(Roles = "Admin,Librarian")]
    public class LoansController : Controller
    {
        private readonly LibraryContext database;
        public LoansController(LibraryContext db)
        {
            database = db;
        }
        public IActionResult Index(int? page)
        {
            var loans = database.Loans.Include(p => p.Book).Include(p => p.Member).ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            int totalItems = loans.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            var item = loans.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View(item);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(LoanViewModel loanData)
        {
            if (loanData != null)
            {
                var book = await database.Books.FirstOrDefaultAsync(s => s.Title == loanData.BookTitle);
                var member = await database.Members.FirstOrDefaultAsync(s => s.Email == loanData.MemberEmail);
                if (book == null || member == null) return View(loanData);
                if (book.Quantity < 1) return BadRequest("This book is out of stock");
                else
                {
                    var loan = new Loan()
                    {
                        LoanDate = loanData.LoanDate,
                        DueDate = loanData.DueDate,
                        BookID = book.BookID,
                        MemberID = member.MemberID,
                        Approved = loanData.Approved,
                        LoanPeriod = (loanData.DueDate - loanData.LoanDate).Days,
                    };
                    database.Loans.Add(loan);
                    await database.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                
            }
            return NotFound();
        }
        public IActionResult ApproveLoan(int id)
        {
            var loan = database.Loans.Find(id);
            ViewBag.Book = database.Books.Find(loan.BookID).Title;
            ViewBag.Member = database.Members.Find(loan.MemberID).Email;
            return View(loan);
        }

        public async Task<IActionResult> LoanApproved(int id)
        {
            var loan = database.Loans.Find(id);
            if (loan != null)
            {
                loan.Approved = true;
                if (loan.LoanDate < DateTime.Now)
                {
                    loan.DueDate = DateTime.Now.AddDays(loan.LoanPeriod);
                }
                var borrowedBook = database.Books.Find(loan.BookID);
                if (borrowedBook != null && loan.ReturnDate == null) borrowedBook.Quantity--;
                await database.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var loan = database.Loans.Find(id);
            if (loan != null)
            {
                return View(loan);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Loan newLoan)
        {
            if (newLoan != null)
            {
                var oldLoan = database.Loans.Find(newLoan.LoanID);
                if (oldLoan != null)
                {
                    oldLoan.ReturnDate = newLoan.ReturnDate;
                    oldLoan.DueDate = newLoan.DueDate;
                    oldLoan.LoanDate = newLoan.LoanDate;
                    oldLoan.LoanPeriod = (newLoan.DueDate - newLoan.LoanDate).Days;

                    // New PenaltyCost
                    if (oldLoan.ReturnDate.HasValue)
                    {
                        oldLoan.PenaltyCost = GetPenaltyCostValue(oldLoan.ReturnDate.Value, oldLoan.DueDate);
                    }
                    else
                    {
                        oldLoan.PenaltyCost = 0;
                    }

                    await database.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult Return(int id)
        {

            var loan = database.Loans.Find(id);
            ViewBag.DueDate = loan.DueDate;
            if (loan.ReturnDate != null) return NoContent();
            if (loan != null)
            {
                return View(loan);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Return(Loan loanData)
        {
            var loan = database.Loans.Find(loanData.LoanID);

            if (loan != null)
            {
                loan.ReturnDate = loanData.ReturnDate;
                if (loan.ReturnDate != null) loan.PenaltyCost = GetPenaltyCostValue(loan.ReturnDate.Value, loan.DueDate);
                loanData.PenaltyCost = loan.PenaltyCost;

                var returnedBook = database.Books.Find(loan.BookID);
                if (returnedBook != null) returnedBook.Quantity++;
                database.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return BadRequest();

        }

        public IActionResult Delete(int id)
        {
            var loan = database.Loans.Find(id);
            if (loan != null)
            {
                ViewBag.BookTitle = database.Books.Find(loan.BookID).Title;
                ViewBag.MemberName = database.Members.Find(loan.MemberID).Email;
                return View(loan);
            }
            return NotFound();
        }

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var loan = database.Loans.Find(id);
            if (loan != null)
            {
                database.Loans.Remove(loan);
                await database.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        private int GetPenaltyCostValue(DateTime returnDate, DateTime dueDate)
        {
            int daysLate = (returnDate.Date - dueDate.Date).Days;
            if (daysLate <= 0)
            {
                return 0;
            }
            int penalty = (int)Math.Ceiling(daysLate / 5.0);
            return penalty;
        }

        [HttpPost]
        public IActionResult PenaltyCost(DateTime returnDate, DateTime dueDate)
        {
            int daysLate = (returnDate - dueDate).Days;
            int penalty = (int)Math.Ceiling(daysLate / 5.0);
            return Json(new { penalty });
        }

        //Search Actions
        public async Task<IActionResult> SearchByTitle(string bookTitle, int? page)
        {
            var loans = database.Loans.Include(p => p.Book).Include(p => p.Member).ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (bookTitle != null)
            {
                var Loans = await database.Loans.Where(b => b.Book.Title.Contains(bookTitle)).ToListAsync();
            }
            int totalItems = loans.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = bookTitle;
            ViewBag.CurrentAction = "SearchByTitle";
            var item = loans.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", loans);
        }
        public async Task<IActionResult> SearchByMember(string member, int? page)
        {
            var loans = database.Loans.Include(p => p.Book).Include(p => p.Member).ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (member != null)
            {
                var Loans = await database.Loans.Where(b => b.Member.Email.Equals(member)).ToListAsync();
            }
            int totalItems = loans.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = member;
            ViewBag.CurrentAction = "SearchByMember";
            var item = loans.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", loans);
        }
        public async Task<IActionResult> SearchByLoanDate(DateTime startdate, DateTime enddate, int? page)
        {
            var loans = database.Loans.Include(p => p.Book).Include(p => p.Member).ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (startdate != null || enddate != null)
            {
                var Loans = await database.Loans.Where(d => d.LoanDate.Day >= startdate.Day && d.LoanDate.Day <= enddate.Day).ToListAsync();
            }
            int totalItems = loans.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = startdate;
            ViewBag.Search2 = enddate;
            ViewBag.CurrentAction = "SearchByLoanDate";
            var item = loans.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", loans);
        }
        public async Task<IActionResult> SearchByDueDate(DateTime startdate, DateTime enddate, int? page)
        {

LibraryMangementSystem/LibraryMangementSystem/Views/Loans/ApproveLoan.cshtml
@model LibraryMangementSystem.Models.Loan

@{
    ViewData["Title"] = "ApproveLoan";
}

<h1>ApproveLoan</h1>

<div>
    <h4>Loan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoanPeriod)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanPeriod)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Approved)
        </dt>
        <dd class = "col-sm-10">
            @(Model.Approved ? "Yes" : "No")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.Book
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.Member
        </dd>
    </dl>
    <form asp-action="LoanApproved" asp-route-id="@Model.LoanID">
        <input type="hidden" asp-for="LoanID" />
        @if (Model.Book.Quantity < 1)
        {
            <input type="submit" value="Approve" class="btn btn-success disabled" />
            <span class="text-danger">This book is out of stock</span>
        }
        else
        {
            <input type="submit" value="Approve" class="btn btn-success" />
        }
         
        <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
    </form>
</div>

LibraryMangementSystem/LibraryMangementSystem/Views/Loans/Create.cshtml
@model LibraryMangementSystem.Models.LoanViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberEmail" class="control-label"></label>
                <input asp-for="MemberEmail" class="form-control" />
                <span asp-validation-for="MemberEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookTitle" class="control-label"></label>
                <input asp-for="BookTitle" class="form-control" />
                <span asp-validation-for="BookTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoanDate" class="control-label"></label>
                <input asp-for="LoanDate" class="form-control" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Approved" checked="checked" /> @Html.DisplayNameFor(model => model.Approved)
                </label>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryMangementSystem/LibraryMangementSystem/Views/Loans/Delete.cshtml
@model LibraryMangementSystem.Models.Loan

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Loan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.BookTitle
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.MemberName
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed" asp-route-id="@Model.LoanID">
        <input type="hidden" asp-for="LoanID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
    </form>
</div>

LibraryMangementSystem/LibraryMangementSystem/Views/Loans/Edit.cshtml
@model LibraryMangementSystem.Models.Loan

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LoanID" />
            

            <div class="form-group">
                <label asp-for="LoanDate" class="control-label"></label>
                <input asp-for="LoanDate" class="form-control" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryMangementSystem/LibraryMangementSystem/Views/Loans/Return.cshtml
@model LibraryMangementSystem.Models.Loan


@{
    var dueDate = ViewBag.DueDate;
}

<h1>Add Return Date</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <p>Due Date: <strong>@dueDate.ToString("yyyy-MM-dd")</strong></p>
        <form asp-action="Return">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <input type="hidden" asp-for="LoanID" value="@Model.LoanID" />
            </div>

            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" onchange="getCost()" id="ReturnDate" class="form-control" min="@Model.LoanDate.ToString("yyyy-MM-dd")"/>
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>

            <label asp-for="PenaltyCost" class="control-label">Penalty Cost: <span id="penaltyCost">0</span>$</label>
            <br />
            <div class="form-group">
                <input type="submit" value="Add Return Date" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
            </div>
        </form>
    </div>

    
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    function getCost() {
        var returnDate = $('#ReturnDate').val();
        var dueDate = '@dueDate';
        $.ajax({
            url: '@Url.Action("PenaltyCost", "Loans")',
            type: 'POST',
            data: { returnDate: returnDate, dueDate: dueDate },
            success: function (response) {
                $('#penaltyCost').text(response.penalty);
            }
        });
    }
</script>