LibraryMangementSystem/LibraryMangementSystem/Models/Book.cs
namespace LibraryMangementSystem.Models
{
    public class Book
    {
        public int BookID { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public int? CategoryID { get; set; }
        public int? PublisherID { get; set; }
        public int? AuthorID { get; set; }
        public int? Quantity { get; set; }
        public double Price { get; set; }
        public byte[]? Cover { get; set; }

        // nav properties
        public Publisher Publisher { get; set; }
        public Category Category { get; set; }
        public ICollection<Loan> Loans { get; set; }
        public Author Author { get; set; }
    }
}

LibraryMangementSystem/LibraryMangementSystem/Controllers/AuthorsController.cs
using LibraryMangementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Core;

namespace LibraryMangementSystem.Controllers
{
    [Authorize(Roles ="Admin, Librarian")]
    public class AuthorsController : Controller
    {
        private readonly LibraryContext database;
        public AuthorsController(LibraryContext db)
        {
            database = db;
        }
        
        public ActionResult Index()
        {
            var authors = database.Authors.ToList();
            return View(authors);
        }

        
        public ActionResult Details(int id)
        {
            var author = database.Authors.Find(id);
            if (author != null) return View(author);
            else return NotFound();
        }
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        
        [HttpPost]
        public async Task<ActionResult> Create(Author author)
        {
            if (author != null)
            {
                author.FullName = author.FirstName + " " + author.LastName;
                database.Authors.Add(author);
                await database.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var author = database.Authors.Find(id);
            if (author != null) return View(author);
            else return NotFound();
        }

        
        [HttpPost]
        
        public async Task<ActionResult> Edit(Author newAuthor)
        {
            if (newAuthor != null)
            {
                var currentAuthor = database.Authors.Find(newAuthor.AuthorID);
                if (currentAuthor != null)
                {
                   
                    currentAuthor.FirstName = newAuthor.FirstName;
                    currentAuthor.LastName = newAuthor.LastName;
                    currentAuthor.FullName = currentAuthor.FirstName + " " + currentAuthor.LastName;
                    await database.SaveChangesAsync();
                    return RedirectToAction("Index");   
                }
            }
            return NotFound();
        }

        
        public ActionResult Delete(int id)
        {
            var author = database.Authors.Find(id);
            return View(author);
        }

        
        [HttpPost]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = database.Authors.Find(id);
            if (author != null)
            {
                database.Authors.Remove(author);
                await database.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }
    }
}

LibraryMangementSystem/LibraryMangementSystem/Controllers/BooksController.cs
using LibraryMangementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryMangementSystem.Controllers
{
    [Authorize(Roles = "Admin,Librarian")]
    public class BooksController : Controller
    {
        private readonly LibraryContext database;
        public BooksController(LibraryContext db)
        {
            database = db;
        }
        public IActionResult Index(int? page)
        {
            var books = database.Books
                .Include(s => s.Publisher)
                .Include(s => s.Category)
                .Include(s => s.Author)
                .ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            int totalItems = books.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            var item = books.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View(item);
        }

        //Search
        public async Task<IActionResult> SearchByTitle(string bookTitle, int? page)
        {
            var books = database.Books
                .Include(s => s.Publisher)
                .Include(s => s.Category)
                .Include(s => s.Author)
                .ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (bookTitle != null)
            {
                books = await database.Books.Where(b => b.Title.Contains(bookTitle)).ToListAsync();
            }
            int totalItems = books.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = bookTitle;
            ViewBag.CurrentAction = "SearchByTitle";
            var item = books.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", item);
        }

        public async Task<IActionResult> SearchByISBN(string bookISBN, int? page)
        {
            var books = database.Books
              .Include(s => s.Publisher)
              .Include(s => s.Category)
              .Include(s => s.Author)
              .ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (bookISBN != null)
            {
                books = await database.Books.Where(b => b.ISBN.StartsWith(bookISBN)).ToListAsync();
            }
            int totalItems = books.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = bookISBN;
            ViewBag.CurrentAction = "SearchByISBN";
            var item = books.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", item);
        }
        public async Task<IActionResult> SearchByCat(string bookCat, int? page)
        {
            var books = database.Books
              .Include(s => s.Publisher)
              .Include(s => s.Category)
              .Include(s => s.Author)
              .ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (bookCat != null)
            {
                books = await database.Books.Where(b => b.Category.Name.StartsWith(bookCat)).ToListAsync();
            }
            int totalItems = books.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = bookCat;
            ViewBag.CurrentAction = "SearchByCat";
            var item = books.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", item);
        }
        public async Task<IActionResult> SearchByPub(string bookPub, int? page)
        {
            var books = database.Books
                .Include(s => s.Publisher)
                .Include(s => s.Category)
                .Include(s => s.Author)
                .ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (bookPub != null)
            {
                books = await database.Books.Where(b => b.Publisher.Name.StartsWith(bookPub)).ToListAsync();
            }
            int totalItems = books.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = bookPub;
            ViewBag.CurrentAction = "SearchByPub";
            var item = books.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", item);
        }
        public async Task<IActionResult> SearchByAuthor(string bookAuthor, int? page)
        {
            var books = database.Books
              .Include(s => s.Publisher)
              .Include(s => s.Category)
              .Include(s => s.Author)
              .ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (bookAuthor != null)
            {
                books = await database.Books.Where(b => b.Author.FullName.Contains(bookAuthor)).ToListAsync();
            }
            int totalItems = books.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = bookAuthor;
            ViewBag.CurrentAction = "SearchByAuthor";
            var item = books.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", item);
        }
        public async Task<IActionResult> SearchByStock(string minStock, string maxStock, int? page)
        {
            var books = database.Books
                .Include(s => s.Publisher)
                .Include(s => s.Category)
                .Include(s => s.Author)
                .ToList();
            int PageSize = 10;
            int PageNumber = (page ?? 1);
            if (minStock != null && maxStock != null)
            {
                books = await database.Books.Where(b => b.Quantity >= Convert.ToInt32(minStock) && b.Quantity <= Convert.ToInt32(maxStock)).ToListAsync();
            }
            int totalItems = books.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / PageSize);
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = PageNumber;
            ViewBag.Search = minStock;
            ViewBag.Search2 = maxStock;
            ViewBag.CurrentAction = "SearchByStock";
            var item = books.Skip((page - 1 ?? 0) * PageSize).Take(PageSize);
            return View("index", item);
        }



        // crud actions
        [HttpGet]
        public IActionResult Create()
        {
            //ViewBag.Pubs = new SelectList(database.Publishers.ToList(), "PublisherID", "Name");
            //ViewBag.Cats = new SelectList(database.Categories.ToList(), "CategoryID", "Name");
            //ViewBag.Authors = new SelectList(database.Authors.ToList(), "AuthorID", "FullName");
            ViewBag.ReturnUrl = Request.GetDisplayUrl();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Book book, IFormFile bookCover, int selectedAuthor, int selectedPublisher, int selectedCategory)
        {
            if (book != null)
            {
                if (bookCover != null)
                {
                    byte[] img;
                    using (var x = bookCover.OpenReadStream())
                    using (var stream = new MemoryStream())
                    {
                        x.CopyTo(stream);
                        img = stream.ToArray();
                    }
                    book.Cover = img;
                }
                book.AuthorID = selectedAuthor;
                book.PublisherID = selectedPublisher;
                book.CategoryID = selectedCategory;
                database.Books.Add(book);
                await database.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        [HttpGet]
        public async Task<IActionResult> SearchAuthors(string searchAuthor)
        {
            var authors = database.Authors;

            var items = await authors
           .Where(i => i.FullName.Contains(searchAuthor))
           .Select(i => new { id = i.AuthorID, text = i.FullName })
           .ToListAsync();

            return Json(items);
        }
        [HttpGet]
        public async Task<IActionResult> SearchPublishers(string searchPublisher)
        {
            var publishers = database.Publishers;

            var items = await publishers
       .Where(i => i.Name.Contains(searchPublisher))
       .Select(i => new { id = i.PublisherID, text = i.Name })
       .ToListAsync();

            return Json(items);
        }
        [HttpGet]
        public async Task<IActionResult> SearchCategories(string searchCategory)
        {
            var publishers = database.Categories;

            var items = await publishers
       .Where(i => i.Name.Contains(searchCategory))
       .Select(i => new { id = i.CategoryID, text = i.Name })
       .ToListAsync();

            return Json(items);
        }

        public FileResult GetCover(int id)
        {
            var book = database.Books.Find(id);
            byte[] img = (byte[])book.Cover.ToArray();
            return File(img, "image/jpeg", "image/png");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            var book = database.Books.Find(id);
            if (book != null)
            {

LibraryMangementSystem/LibraryMangementSystem/Views/Books/Create.cshtml
@model LibraryMangementSystem.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Add New Book</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="categorySearch">Category</label>
                <input id="categorySearch" type="text" name="searchCategory" class="form-control">
            </div>
            <div class="form-group">
                <div class="d-flex">
                    <select id="categoryList" name="selectedCategory" class="form-control mt-2 me-2">
                        <option value="">Select an option</option>
                    </select>
                    <a asp-controller="Categories" asp-action="Create" class="btn btn-sm btn-outline-secondary text-center mt-2 text-nowrap">Add New</a>
                </div>
            </div>

            <div class="form-group">
                <label for="publisherSearch">Publisher</label>
                <input id="publisherSearch" type="text" name="searchPublisher" class="form-control">
            </div>
            <div class="form-group">
                <div class="d-flex">
                    <select id="publisherList" name="selectedPublisher" class="form-control mt-2 me-2">
                        <option value="">Select an option</option>
                    </select>
                    <a asp-controller="Publishers" asp-action="Create" class="btn btn-sm btn-outline-secondary mt-2 text-nowrap">Add New</a>
                </div>
            </div>

            <div class="form-group">
                <label for="authorSearch">Author</label>
                <input id="authorSearch" type="text" name="searchAuthor" class="form-control">
            </div>
            <div class="form-group">
                <div class="d-flex">
                    <select id="authorList" name="selectedAuthor" class="form-control mt-2 me-2">
                        <option value="">Select an option</option>
                    </select>
                    <a asp-controller="Authors" asp-action="Create" aspr class="btn btn-sm btn-outline-secondary mt-2 text-nowrap">Add New</a>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group mt-2">
                <label asp-for="Cover" class="control-label"></label>
                <input type="file" name="bookCover" accept="image/jpeg, image/png" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
            </div>

        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $('#authorSearch').on('keyup', function () {
            var searchAuthor = $(this).val();

            if (searchAuthor.length >= 1) {
                $.ajax({
                    url: '@Url.Action("SearchAuthors", "Books")',
                    data: { searchAuthor: searchAuthor },
                    success: function (data) {
                        var dropdown = $('#authorList');
                        dropdown.empty();

                        $.each(data, function (i, item) {
                            dropdown.append($('<option>', { value: item.id, text: item.text }));
                        });
                    },
                    error: function () {
                        alert('Error occurred while searching.');
                    }
                });
            }
        });
        $('#publisherSearch').on('keyup', function () {
            var searchPublisher = $(this).val();

            if (searchPublisher.length >= 1) {
                $.ajax({
                    url: '@Url.Action("SearchPublishers", "Books")',
                    data: { searchPublisher: searchPublisher },
                    success: function (data) {
                        var dropdown = $('#publisherList');
                        dropdown.empty();

                        $.each(data, function (i, item) {
                            dropdown.append($('<option>', { value: item.id, text: item.text }));
                        });
                    },
                    error: function () {
                        alert('Error occurred while searching.');
                    }
                });
            }
        });
        $('#categorySearch').on('keyup', function () {
            var searchCategory = $(this).val();

            if (searchCategory.length >= 1) {
                $.ajax({
                    url: '@Url.Action("SearchCategories", "Books")',
                    data: { searchCategory: searchCategory },
                    success: function (data) {
                        var dropdown = $('#categoryList');
                        dropdown.empty();

                        $.each(data, function (i, item) {
                            dropdown.append($('<option>', { value: item.id, text: item.text }));
                        });
                    },
                    error: function () {
                        alert('Error occurred while searching.');
                    }
                });
            }
        });
    });

</script>

LibraryMangementSystem/LibraryMangementSystem/Views/Books/Delete.cshtml
@model LibraryMangementSystem.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cover)
        </dt>
        <dt class="col-sm-10">
            <img src="/Books/GetCover/@Model?.BookID" style="width:200px;height:200px" />
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.AuthorName
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        
        <dd class = "col-sm-10">
            <span>$</span>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.PublisherName
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.CategoryName
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed" asp-route-id="@Model.BookID">
        <input type="hidden" asp-for="BookID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
    </form>
</div>

LibraryMangementSystem/LibraryMangementSystem/Views/Books/Details.cshtml
@model LibraryMangementSystem.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cover)
        </dt>
        <dt class="col-sm-10">
            <img src="/Books/GetCover/@Model?.BookID" style="width:200px;height:200px" />
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.AuthorName
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            <span>$</span>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.PublisherName
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.CategoryName
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BookID" class="btn btn-outline-primary">Edit</a> 
    <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
</div>

LibraryMangementSystem/LibraryMangementSystem/Views/Books/Edit.cshtml
@model LibraryMangementSystem.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookID" />
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input type="file" name="bookCover" accept="image/jpeg, image/png" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="categorySearch">Category</label>
                <input id="categorySearch" type="text"  name="searchCategory" class="form-control">
            </div>
            <div class="form-group">
                <select id="categoryList" name="selectedCategory" class="form-control">
                    <option value="">Select an option</option>
                </select>
            </div>

            <div class="form-group">
                <label for="publisherSearch">Publisher</label>
                <input id="publisherSearch" type="text" name="searchPublisher" class="form-control">
            </div>
            <div class="form-group">
                <select id="publisherList" name="selectedPublisher" class="form-control">
                    <option value="">Select an option</option>
                </select>
            </div>

            <div class="form-group">
                <label for="authorSearch">Author</label>
                <input id="authorSearch" type="text" name="searchAuthor" class="form-control">
            </div>
            <div class="form-group">
                <select id="authorList" name="selectedAuthor" class="form-control">
                    <option value="">Select an option</option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
<br />
<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $('#authorSearch').on('keyup', function () {
            var searchAuthor = $(this).val();

            if (searchAuthor.length >= 1) {
                $.ajax({
                    url: '@Url.Action("SearchAuthors", "Books")',
                    data: { searchAuthor: searchAuthor },
                    success: function (data) {
                        var dropdown = $('#authorList');
                        dropdown.empty();

                        $.each(data, function (i, item) {
                            dropdown.append($('<option>', { value: item.id, text: item.text }));
                        });
                    },
                    error: function () {
                        alert('Error occurred while searching.');
                    }
                });
            }
        });
        $('#publisherSearch').on('keyup', function () {
            var searchPublisher = $(this).val();

            if (searchPublisher.length >= 1) {
                $.ajax({
                    url: '@Url.Action("SearchPublishers", "Books")',
                    data: { searchPublisher: searchPublisher },
                    success: function (data) {
                        var dropdown = $('#publisherList');
                        dropdown.empty();

                        $.each(data, function (i, item) {
                            dropdown.append($('<option>', { value: item.id, text: item.text }));
                        });
                    },
                    error: function () {
                        alert('Error occurred while searching.');
                    }
                });
            }
        });
        $('#categorySearch').on('keyup', function () {
            var searchCategory = $(this).val();

            if (searchCategory.length >= 1) {
                $.ajax({
                    url: '@Url.Action("SearchCategories", "Books")',
                    data: { searchCategory: searchCategory },
                    success: function (data) {
                        var dropdown = $('#categoryList');
                        dropdown.empty();

                        $.each(data, function (i, item) {
                            dropdown.append($('<option>', { value: item.id, text: item.text }));
                        });
                    },
                    error: function () {
                        alert('Error occurred while searching.');
                    }
                });
            }
        });
    });

</script>